---
title: "La Liga Mid-Season Review"
output: 
  html_document:
    theme: yeti
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r }
library(worldfootballR)
library(forcats)
require(tidyverse)

teams_results <- understat_league_match_results('La liga', 2021) %>%
  select(match_id, home_team, away_team, home_goals, away_goals, home_xG, away_xG)

teams <- understat_league_match_results('La liga', 2021) %>%
  select(home_team)

teams <- unique(teams)


out <- data.frame(
    team = character(),
    points = numeric(),
    expected_points = numeric()
)

for (i in 1:nrow(teams)) {
  points <- 0
  expected_points <- 0
  
  for(j in 1:nrow(teams_results)){
    
    if(teams$home_team[i] == teams_results$home_team[j]){
      if (teams_results$home_goals[j] > teams_results$away_goals[j])
        points <- points+3
      else if (teams_results$home_goals[j] == teams_results$away_goals[j])
        points <- points + 1
    }
    
    if(teams$home_team[i] == teams_results$away_team[j]){
      if (teams_results$away_goals[j] > teams_results$home_goals[j])
        points <- points+3
      else if (teams_results$away_goals[j] == teams_results$home_goals[j])
        points <- points + 1
    }
    
    if(teams$home_team[i] == teams_results$home_team[j]){
      if (teams_results$home_xG[j] > teams_results$away_xG[j])
        expected_points <- expected_points+3
      else if (teams_results$home_xG[j] == teams_results$away_xG[j])
        expected_points <- expected_points + 1
    }
    
    if(teams$home_team[i] == teams_results$away_team[j]){
      if (teams_results$away_xG[j] > teams_results$home_xG[j])
        expected_points <- expected_points+3
      else if (teams_results$away_xG[j] == teams_results$home_xG[j])
        expected_points <- expected_points + 1
      }
  }
  out <- rbind(out,new <- data.frame(teams$home_team[i], points, expected_points))
}

colnames(out) <- c('team', 'points', 'expected_points')

```


```{r}
underperformers <- out %>% 
  mutate(difference = points - expected_points) %>%
  arrange(difference)%>%
  head(5) %>%
  mutate(difference = abs(difference)) %>%
  arrange()

ggplot(underperformers, aes(x= fct_inorder(team), y = difference)) +

    geom_line(group=1, color = "blue") + 
  xlab('Teams') + ylab('Difference in Points') +annotate("text",x = 2, y = 30, label =
                                                           "Underperforming teams by points")
```


```{r}

overperformers <- out %>% 
  mutate(difference = expected_points - points) %>%
  arrange(difference)%>%
  head(5) %>%
  arrange(desc(difference))

ggplot(overperformers, aes(x= fct_inorder(team), y = difference)) +
  geom_line(group=1, color = "blue") + 
  xlab('Teams') + ylab('Difference in Points') +annotate("text",x = 2, y = 30, label = "Overperforming teams by points")

```